### ISSUE TITLE
Problem getting bootstrap resource glyph images

### ISSUE THREAD

**Issue by raix** [awwx/meteor-appcache#1]
Getting an error in console, if I uninstall appcache then no error, if I reinstalls then no errors - it fetches all again.

If I refresh I get:

One error in client console: _(I'm guessing this is some path thing?)_

```
GET http://localhost:3000/packages/bootstrap/img/glyphicons-halflings.png  localhost:184
```

I'm running 0.5.6 - and bootstrap.

EDIT:
I tried out the path `http://localhost:3000/packages/bootstrap/img/glyphicons-halflings.png` works fine - wonder if it's not in appcache?

**Comment by awwx** [comment]
Hmm, I think I know what that might be... I'll take a look.

**Comment by awwx** [comment]
Confirmed: images from packages aren't being added to the app cache manifest.

**Comment by awwx** [comment]
Fixed, added to Meteor PR https://github.com/meteor/meteor/pull/720

**Comment by raix** [comment]
Great thanks!
