### ISSUE TITLE
has this been abandoned?

### ISSUE THREAD

**Issue by dheerajbhaskar** [awwx/meteor-appcache#3]
All repos/packages of appcache seem to be really old (last commit 1+ year ago). Please help find one that works now.

Or is the appcache route to make meteor apps faster not suggested now? What is a better method to decrease first visit times?

**Comment by ianserlin** [comment]
Meteor has first class appcache support built in now. See http://docs.meteor.com/#/full/appcache

**Comment by dheerajbhaskar** [comment]
I'm sorry if this seems silly. Does that mean I should remove this package?

On the link you've mentioned that I need to add the appcache package. I
read in on of the mail threads that this would be the officially maintained
repo.

I'm not sure what to do to enable appcache in meteor. Kindly help.

**Comment by dheerajbhaskar** [comment]
I just did

Meteor add appcache

Let me know if that's the right way.

**Comment by ianserlin** [comment]
Yup, you should remove this package and then just `meteor add appcache`. There are additional configuration options as described in http://docs.meteor.com/#/full/appcache.

@awwx maybe put a link/headsup in the readme for this package?

**Comment by dheerajbhaskar** [comment]
Thanks @ianserlin 
I think a headsup in readme that would really help @awwx
